### ISSUE TITLE
No reconstructed event with the ellipsis method

### ISSUE THREAD

**Issue by rmadar** [rmadar/go-topquark-reco#14]
Hi @sbinet, thanks again for the go version of the ellipse method! I think there might be an issue though since no events are reconstructed right now - and I feel it's a little suspicious.
```
./demo -reco ell
Number of events w/o reconstruction: 100

./demo -reco sonn
Number of events w/o reconstruction: 91
```
(also note that I have slightly changed your code to remove masses - but I have tested it before these changes)

**Comment by rmadar** [comment]
(I have found weird things running sonnenschein with the C++ code and the go code using the same file. Something weirder than small differences we saw in the past. I am checking this first.)

**Comment by rmadar** [comment]
Alright, it was stupid bug. I have updated `testdata/data.root` in this repository so that both codes can be ran on the exact same events. This is what I get now for the number of events for which the reconstruction fails:

|    | C++ | go |
|:--|-------:|----:| 
| Son. |  82 |  82 |
| Ell.   |  70 |  100 |

**Comment by sbinet** [comment]
I am still going through this (`diff -urN cxx.txt go.txt`).

one thing which I've just noticed is a probable bug in C++ in how the rotation matrix is computed:

```c++
TMatrixD NeutrinoEllipseCalculator::rotationMatrix(int axis, double angle)
{
        printf("rot-matrix(%d, %+2.15e)...\n", axis, angle);
  TMatrixD r(3,3);
  r.Zero();
  if (axis!=0 && axis!=1 && axis!=2) return r;
  
  for( int i=0; i<3; i++ ) 
    {
      r[i][i]=cos(angle);
          printf("r[%d][%d]=%+2.8e\n", i,i,r[i][i]);
    }

  for( int ii=-1; ii<=1; ii++ )  
    {
                int j = ii;
      double row=(axis-ii)%3; if(row<0) row+=3;
      double col=(axis+ii)%3; if(col<0) col+=3;
      r[row][col]=ii*sin(angle)+(1-ii*ii);
          printf("r[%d][%d][i=%ld]=%+2.8e\n", row,col,j,r[row][col]);
    }

  return r;
}
```

which yields:
```
rot-matrix(2, +2.516797540058885e+00)...
r[0][0]=-8.11082981e-01
r[1][1]=-8.11082981e-01
r[2][2]=-8.11082981e-01
r[-1][-1][i=140720359178528]=+0.00000000e+00
r[0][0][i=140720359178528]=+2.00000000e+00
r[1][1][i=140720359178528]=+1.00000000e+00
```

so... it looks like an out of bound access read+write.

**Comment by sbinet** [comment]
I must say that, when I'd translated that code to Go, I was a bit surprised.
perhaps I am not completly okay on what `::rotationMatrix` is supposed to do, but I was actually expecting rotation matrices like:
https://en.wikipedia.org/wiki/Rotation_matrix#Basic_rotations

![rot](https://wikimedia.org/api/rest_v1/media/math/render/svg/a6821937d5031de282a190f75312353c970aa2df)

**Comment by rmadar** [comment]
ok, I see ... Quickly looking at the C++ code you put in your comment, I tend to be confused as well. I'll try to further look at this, and come back to you on this.

But just a simple question: how is it possible to print a value of `j` which is `140720359178528` while `j` is defined above as being `ii`, which is `[-1, 0, 1]` - and never modified after? (unless `%ld` has special meaning which is not the value of `j`?).

**Comment by sbinet** [comment]
>  But just a simple question: how is it possible to print a value of j which is 140720359178528 while j is defined above as being ii, which is [-1, 0, 1] - and never modified after? (unless %ld has special meaning which is not the value of j?).

that's indeed where I've started to suspect a buffer overwrite :)
(`%ld` is just "print that decimal number with long precision")

**Comment by rmadar** [comment]
heu ... ok but then how can we solve this? I mean, it has nothing to do with a mathematically wrong result/expression. This is purely related to the code, right? I don't think I have ever meet such a problem (where a variable is modified while I didn't ask for it).

**Comment by sbinet** [comment]
it's because _e.g._ when `i=-1`, we may end-up with `row=-1, col=-1`.
this will end-up trying to access memory *before* the start of the underlying array making the matrix `r`.
it seems we clobber the memory area assigned to the loop variable `i`.

also, I do believe there's -on top of the previous error- a mathematical error.
if one take the `Rz` case (ie: `axis=2`), the expected rotation matrix, according to the above wikipedia article (the source of all knowledge in the known universe), would be:
```
[cos, -sin, 0, 
 sin, cos, 0,
 0, 0, 1]
```

but we get:
```
[2 (initially cos), 0, 0,
 0, 1 (initially cos), 0,
 0, 0, cos]
```

**Comment by rmadar** [comment]
OK, I see. Is the first error easy to correct (I am asking because .. well, because I don't know!)?

I would be in favour of fixing the first error, trying the reconstruction again, and see if we get the same result a the C++ code - before fixing the second error. My suspicion here is that it might be a misleading naming rather than an actual mathematical error (because the obtained results make sense, physically). Once we reproduce C++ result, I can iterate with the original authors on this rotation matrix.

Does that make sense?

**Comment by sbinet** [comment]
I think the first item of order is to actually know what that method is supposed to do.

**Comment by rmadar** [comment]
Yes, this is a good plan (in general). The problem in that case is that this matrix was coded 7 years ago [here](https://github.com/betchart/analytic-nu/blob/34885ed00a88706ea414f96b41a8ea151992314a/NeutrinoEllipseCalculator.C#L167-L186) and there is chance that people are not around anymore - but it doesn't hurt to ask! There is another version in python of the same fonction [here](https://github.com/betchart/analytic-nu/blob/34885ed00a88706ea414f96b41a8ea151992314a/nuSolutions.py#L25-L31) - if that helps.

If no one replies to me, I guess we might need a bit of an heuristic approach here - unless we want to start from scratch and read/understand the paper, which I am not really in favour of.

**Comment by sbinet** [comment]
looking at the paper:
https://arxiv.org/pdf/1305.1878.pdf

it seems the expected rotation matrix is indeed what the wikipedia page is refering to.
(see p7, the `R` method from the python reference implementation)

```python
>>> import math
>>> fff.R(0, math.pi/6.)
array([[ 1.       ,  0.       ,  0.       ],
       [ 0.       ,  0.8660254, -0.5      ],
       [ 0.       ,  0.5      ,  0.8660254]])
>>> fff.R(2, math.pi/6.)
array([[ 0.8660254, -0.5      ,  0.       ],
       [ 0.5      ,  0.8660254,  0.       ],
       [ 0.       ,  0.       ,  1.       ]])
```

```python
## file: fff.py
import math
import numpy as np

def R(axis , angle ):
    """
    Rotation matrix about x(0),y(1), or z(2) axis
    """
    c, s = math.cos(angle), math.sin(angle)
    R = c * np.eye (3)
    for i in [-1, 0, 1]:
        R[(axis -i)%3, (axis+i)%3] = i*s + (1 - i*i)
    return R
```

**Comment by rmadar** [comment]
OK the logic seems to be correct in python but not in C++, so indeed I am convinced this should be corrected :+1:

**Comment by rmadar** [comment]
> also, I do believe there's -on top of the previous error- a mathematical error.
> if one take the `Rz` case (ie: `axis=2`), the expected rotation matrix, according to the above wikipedia article (the source of all knowledge in the known universe), would be:
> 
> ```
> [cos, -sin, 0, 
>  sin, cos, 0,
>  0, 0, 1]
> ```
> 
> but we get:
> 
> ```
> [2 (initially cos), 0, 0,
>  0, 1 (initially cos), 0,
>  0, 0, cos]
> ```

Coming back to the original math problem, I can't reproduce it:
```
root [1] .L NeutrinoEllipseCalculator.C+
root [2] .x testRotationMatrix.C

3x3 matrix is as follows

     |      0    |      1    |      2    |
--------------------------------------------
   0 |      0.866        -0.5           0 
   1 |        0.5       0.866           0 
   2 |          0           0           1 
```

where `testRotationMatrix.C` is
```cpp
{
  NeutrinoEllipseCalculator NE; 
  auto M = NE.rotationMatrix(2, TMath::Pi()/6.); 
  M.Print(); 
}
```

So I don't know what was happening in your example, but the C++ code seems to work properly. At the end:
 1. I don't think  it makes a difference with your new implementation in https://github.com/rmadar/go-topquark-reco/pull/15 (it just does the same)
 2. we should probably get 70 events failing the reconstruction.

**Comment by sbinet** [comment]
FYI, regarding the rotation matrix, I believe it was an issue with a switch statement I had added.
I haven't dug through in detail. (And it's kind of moot anyways)
